/// Mapowanie kod-kraju → nowe, wycięte znaczki `CountryStamp*` (09.09.2026,
/// prawdziwy styl referencyjnego mockupu plakatu "My Travel Journey" —
/// kolorowa cienka obwódka + ilustracja linearna + nazwa, zamiast
/// dotychczasowych naklejek Travel Passport, inna rodzina wizualna).
/// Wygenerowane programowo z 215 wyciętych znaczków (dopasowanie do
/// istniejącego `worldStickerAssetByCountryCode` po znormalizowanej
/// nazwie) — kraje spoza tego zestawu (drobne terytoria zamorskie, nigdy
/// nie było ich na wyciętych arkuszach) celowo pominięte, `stampsRow`
/// spada wtedy na stary `worldStickerAssetByCountryCode`/flagę.
let journeyStampAssetByCountryCode: [String: String] = [
    "AD": "CountryStampAndorra", "AE": "CountryStampUnitedArabEmirates", "AF": "CountryStampAfghanistan",
    "AG": "CountryStampAntiguaAndBarbuda", "AL": "CountryStampAlbania", "AM": "CountryStampArmenia",
    "AO": "CountryStampAngola", "AQ": "CountryStampAntarctica", "AR": "CountryStampArgentina",
    "AS": "CountryStampAmericanSamoa", "AT": "CountryStampAustria", "AU": "CountryStampAustralia",
    "AZ": "CountryStampAzerbaijan", "BA": "CountryStampBosniaAndHerzegovina", "BB": "CountryStampBarbados",
    "BD": "CountryStampBangladesh", "BE": "CountryStampBelgium", "BF": "CountryStampBurkinaFaso",
    "BG": "CountryStampBulgaria", "BH": "CountryStampBahrain", "BI": "CountryStampBurundi",
    "BJ": "CountryStampBenin", "BN": "CountryStampBrunei", "BO": "CountryStampBolivia",
    "BR": "CountryStampBrazil", "BS": "CountryStampBahamas", "BT": "CountryStampBhutan",
    "BW": "CountryStampBotswana", "BY": "CountryStampBelarus", "BZ": "CountryStampBelize",
    "CA": "CountryStampCanada", "CD": "CountryStampDemocraticRepublicOfTheCongo", "CF": "CountryStampCentralAfricanRepublic",
    "CG": "CountryStampRepublicOfTheCongo", "CH": "CountryStampSwitzerland", "CI": "CountryStampCoteDIvoire",
    "CL": "CountryStampChile", "CM": "CountryStampCameroon", "CN": "CountryStampChina",
    "CO": "CountryStampColombia", "CR": "CountryStampCostaRica", "CU": "CountryStampCuba",
    "CV": "CountryStampCaboVerde", "CY": "CountryStampCyprus", "CZ": "CountryStampCzechia",
    "DE": "CountryStampGermany", "DJ": "CountryStampDjibouti", "DK": "CountryStampDenmark",
    "DM": "CountryStampDominica", "DO": "CountryStampDominicanRepublic", "DZ": "CountryStampAlgeria",
    "EC": "CountryStampEcuador", "EE": "CountryStampEstonia", "EG": "CountryStampEgypt",
    "ER": "CountryStampEritrea", "ES": "CountryStampSpain", "ET": "CountryStampEthiopia",
    "FI": "CountryStampFinland", "FJ": "CountryStampFiji", "FM": "CountryStampMicronesia",
    "FR": "CountryStampFrance", "GA": "CountryStampGabon", "GB-ENG": "CountryStampEngland",
    "GB-NIR": "CountryStampNorthernIreland", "GB-SCT": "CountryStampScotland", "GB-WLS": "CountryStampWales",
    "GD": "CountryStampGrenada", "GE": "CountryStampGeorgia", "GH": "CountryStampGhana",
    "GL": "CountryStampGreenland", "GM": "CountryStampGambia", "GN": "CountryStampGuinea",
    "GQ": "CountryStampEquatorialGuinea", "GR": "CountryStampGreece", "GT": "CountryStampGuatemala",
    "GW": "CountryStampGuineaBissau", "GY": "CountryStampGuyana", "HN": "CountryStampHonduras",
    "HR": "CountryStampCroatia", "HT": "CountryStampHaiti", "HU": "CountryStampHungary",
    "ID": "CountryStampIndonesia", "IE": "CountryStampIreland", "IL": "CountryStampIsrael",
    "IN": "CountryStampIndia", "IQ": "CountryStampIraq", "IR": "CountryStampIran",
    "IS": "CountryStampIceland", "IT": "CountryStampItaly", "JM": "CountryStampJamaica",
    "JO": "CountryStampJordan", "JP": "CountryStampJapan", "KE": "CountryStampKenya",
    "KG": "CountryStampKyrgyzstan", "KH": "CountryStampCambodia", "KI": "CountryStampKiribati",
    "KM": "CountryStampComoros", "KN": "CountryStampSaintKittsAndNevis", "KP": "CountryStampNorthKorea",
    "KR": "CountryStampSouthKorea", "KW": "CountryStampKuwait", "KZ": "CountryStampKazakhstan",
    "LA": "CountryStampLaos", "LB": "CountryStampLebanon", "LC": "CountryStampSaintLucia",
    "LI": "CountryStampLiechtenstein", "LK": "CountryStampSriLanka", "LR": "CountryStampLiberia",
    "LS": "CountryStampLesotho", "LT": "CountryStampLithuania", "LU": "CountryStampLuxembourg",
    "LV": "CountryStampLatvia", "LY": "CountryStampLibya", "MA": "CountryStampMorocco",
    "MC": "CountryStampMonaco", "MD": "CountryStampMoldova", "ME": "CountryStampMontenegro",
    "MG": "CountryStampMadagascar", "MH": "CountryStampMarshallIslands", "MK": "CountryStampNorthMacedonia",
    "ML": "CountryStampMali", "MM": "CountryStampMyanmar", "MN": "CountryStampMongolia",
    "MR": "CountryStampMauritania", "MT": "CountryStampMalta", "MU": "CountryStampMauritius",
    "MV": "CountryStampMaldives", "MW": "CountryStampMalawi", "MX": "CountryStampMexico",
    "MY": "CountryStampMalaysia", "MZ": "CountryStampMozambique", "NA": "CountryStampNamibia",
    "NC": "CountryStampNewCaledonia", "NE": "CountryStampNiger", "NG": "CountryStampNigeria",
    "NI": "CountryStampNicaragua", "NL": "CountryStampNetherlands", "NO": "CountryStampNorway",
    "NP": "CountryStampNepal", "NR": "CountryStampNauru", "NZ": "CountryStampNewZealand",
    "OM": "CountryStampOman", "PA": "CountryStampPanama", "PE": "CountryStampPeru",
    "PG": "CountryStampPapuaNewGuinea", "PH": "CountryStampPhilippines", "PK": "CountryStampPakistan",
    "PL": "CountryStampPoland", "PS": "CountryStampPalestine", "PT": "CountryStampPortugal",
    "PW": "CountryStampPalau", "PY": "CountryStampParaguay", "QA": "CountryStampQatar",
    "RO": "CountryStampRomania", "RS": "CountryStampSerbia", "RU": "CountryStampRussia",
    "RW": "CountryStampRwanda", "SA": "CountryStampSaudiArabia", "SB": "CountryStampSolomonIslands",
    "SC": "CountryStampSeychelles", "SD": "CountryStampSudan", "SE": "CountryStampSweden",
    "SG": "CountryStampSingapore", "SI": "CountryStampSlovenia", "SK": "CountryStampSlovakia",
    "SL": "CountryStampSierraLeone", "SM": "CountryStampSanMarino", "SN": "CountryStampSenegal",
    "SO": "CountryStampSomalia", "SR": "CountryStampSuriname", "SS": "CountryStampSouthSudan",
    "ST": "CountryStampSaoTomeAndPrincipe", "SV": "CountryStampElSalvador", "SY": "CountryStampSyria",
    "SZ": "CountryStampEswatini", "TD": "CountryStampChad", "TG": "CountryStampTogo",
    "TH": "CountryStampThailand", "TJ": "CountryStampTajikistan", "TL": "CountryStampTimorLeste",
    "TM": "CountryStampTurkmenistan", "TN": "CountryStampTunisia", "TO": "CountryStampTonga",
    "TR": "CountryStampTurkiye", "TT": "CountryStampTrinidadAndTobago", "TV": "CountryStampTuvalu",
    "TW": "CountryStampTaiwan", "TZ": "CountryStampTanzania", "UA": "CountryStampUkraine",
    "UG": "CountryStampUganda", "US": "CountryStampUnitedStates", "UY": "CountryStampUruguay",
    "UZ": "CountryStampUzbekistan", "VA": "CountryStampVaticanCity", "VC": "CountryStampSaintVincentAndTheGrenadines",
    "VE": "CountryStampVenezuela", "VN": "CountryStampVietnam", "VU": "CountryStampVanuatu",
    "WS": "CountryStampSamoa", "XK": "CountryStampKosovo", "YE": "CountryStampYemen",
    "ZA": "CountryStampSouthAfrica", "ZM": "CountryStampZambia", "ZW": "CountryStampZimbabwe",
    // 11.09.2026: terytoria zamorskie z nowych arkuszy znaczków
    "AW": "CountryStampAruba",
    "BM": "CountryStampBermuda",
    "BQ": "CountryStampBonaire",
    "CW": "CountryStampCuracao",
    "FK": "CountryStampFalklandIslands",
    "GF": "CountryStampFrenchGuiana",
    "PR": "CountryStampPuertoRico",
    "BL": "CountryStampSaintBarthelemy",
    "MF": "CountryStampSaintMartin",
    "PM": "CountryStampSaintPierreandMiquelon",
]
